spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/community
        username: community_user
        password: change-me

    devtools:
        livereload:
            enabled: true

    jpa:
        hibernate:
            ddl-auto: update # 개발용; 운영은 validate + Flyway 권장
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            mode: never

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: YOUR_GOOGLE_CLIENT_ID
                        client-secret: YOUR_GOOGLE_CLIENT_SECRET
                        scope: [email, profile]
                    github:
                        client-id: YOUR_GITHUB_CLIENT_ID
                        client-secret: YOUR_GITHUB_CLIENT_SECRET
                        scope: [user:email]
                    naver:
                        client-id: YOUR_NAVER_CLIENT_ID
                        client-secret: YOUR_NAVER_CLIENT_SECRET
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/naver"
                        scope: [name, email]
                        client-name: Naver
                        provider: naver
                    kakao:
                        client-id: YOUR_KAKAO_REST_API_KEY
                        client-secret: "" # 카카오는 보통 secret 없이도 동작
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
                        scope: [profile_nickname, account_email]
                        client-name: Kakao
                        provider: kakao
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

server:
    error:
        include-message: always
    port: 8088

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
    secret: "replace-with-a-very-long-random-secret-at-least-32-bytes"
    access-token-validity-seconds: 900
    refresh-token-validity-seconds: 1209600
