name: Deploy to EC2

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Build JAR
              run: |
                  chmod +x gradlew
                  ./gradlew build -x test

            - name: Build Docker Image
              run: |
                  docker build -t studio-project-backend .

            - name: Save Docker Image
              run: |
                  docker save studio-project-backend > studio-project-backend.tar

            - name: Copy to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: studio-project-backend.tar
                  target: /home/ubuntu/

            - name: Deploy on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      docker stop studio-project-backend || true
                      docker rm studio-project-backend || true

                      docker load < /home/ubuntu/studio-project-backend.tar

                      docker run -d --name studio-project-backend -p 8080:8080 studio-project-backend

                      rm /home/ubuntu/studio-project-backend.tar
